/**
 * Nomes de instituições financeiras (SPI / Pix / repasse) para seleção no cadastro.
 * Lista ampla (comerciais, cooperativas, pagamentos); ordem alfabética em runtime.
 */
const RAW: readonly string[] = [
  "Acesso Soluções de Pagamento S.A.",
  "Advanced Corretora de Câmbio Ltda.",
  "Alipay Brasil Instituição de Pagamento Ltda.",
  "Banco ABC Brasil S.A.",
  "Banco Agibank S.A.",
  "Banco Alfa S.A.",
  "Banco Andbank (Brasil) S.A.",
  "Banco Arbi S.A.",
  "Banco B3 S.A.",
  "Banco BMG S.A.",
  "Banco BNP Paribas Brasil S.A.",
  "Banco Bradesco S.A.",
  "Banco Bradesco Cartões S.A.",
  "Banco BS2 S.A.",
  "Banco BTG Pactual S.A.",
  "Banco C6 S.A.",
  "Banco Caixa Geral – Brasil S.A.",
  "Banco Capital S.A.",
  "Banco Cetelem S.A.",
  "Banco Citibank S.A.",
  "Banco Cooperativo Sicredi S.A.",
  "Banco Cooperativo do Brasil S.A. – Bancoob / Sicoob",
  "Banco Credit Agricole Brasil S.A.",
  "Banco CSF S.A.",
  "Banco da Amazonia S.A.",
  "Banco da China Brasil S.A.",
  "Banco Daycoval S.A.",
  "Banco Digimais S.A.",
  "Banco Digio S.A.",
  "Banco do Brasil S.A.",
  "Banco do Estado de Sergipe S.A. – Banese",
  "Banco do Estado do Pará S.A.",
  "Banco do Nordeste do Brasil S.A.",
  "Banco Fibra S.A.",
  "Banco Finaxis S.A.",
  "Banco Genial S.A.",
  "Banco Guanabara S.A.",
  "Banco Inbursa S.A.",
  "Banco Industrial do Brasil S.A.",
  "Banco Inter S.A.",
  "Banco Investcred Unibanco S.A.",
  "Banco Itaú BBA S.A.",
  "Banco Itaú Consignado S.A.",
  "Banco Itaú Unibanco S.A.",
  "Banco J. Safra S.A.",
  "Banco John Deere S.A.",
  "Banco KDB do Brasil S.A.",
  "Banco Luso Brasileiro S.A.",
  "Banco Master S.A.",
  "Banco Mercantil do Brasil S.A.",
  "Banco Modal S.A.",
  "Banco Morgan Stanley S.A.",
  "Banco MUFG Brasil S.A.",
  "Banco Original S.A.",
  "Banco Pan S.A.",
  "Banco Paulista S.A.",
  "Banco Pine S.A.",
  "Banco Rabobank International Brasil S.A.",
  "Banco Randon S.A.",
  "Banco Rendimento S.A.",
  "Banco Rodobens S.A.",
  "Banco Safra S.A.",
  "Banco Santander (Brasil) S.A.",
  "Banco Semear S.A.",
  "Banco Simples S.A.",
  "Banco Sofisa S.A.",
  "Banco Sumitomo Mitsui Brasileiro S.A.",
  "Banco Topázio S.A.",
  "Banco Triângulo S.A.",
  "Banco Votorantim S.A.",
  "Banco Western Union do Brasil S.A.",
  "Banco XP S.A.",
  "Bari Companhia Hipotecária",
  "BMG Seguros S.A.",
  "BRB – Banco de Brasília S.A.",
  "Caixa Econômica Federal",
  "Citibank N.A.",
  "Cooperativa Central de Crédito – Ailos",
  "Cooperativa de Crédito Rural de Abelardo Luz – Sulcredi/Crediluz",
  "Credialiança Cooperativa de Crédito Rural",
  "Credisan – Cooperativa de Crédito",
  "Crefisa S.A. Crédito Financiamento e Investimentos",
  "Dock Instituição de Pagamento S.A.",
  "Facta Financeira S.A. Crédito Financiamento e Investimento",
  "Gerencianet Pagamentos do Brasil Ltda.",
  "Guide Investimentos S.A. Corretora de Valores",
  "Hipercard Banco Múltiplo S.A.",
  "HS Financeira S.A. Crédito Financiamento e Investimentos",
  "IB Corretora de Câmbio, Títulos e Valores Mobiliários S.A.",
  "Infinite Pay Instituição de Pagamento Ltda.",
  "Inteligo Corretora de Câmbio Ltda.",
  "Itaú Unibanco Holding S.A.",
  "Mercado Pago Instituição de Pagamento Ltda.",
  "Money Plus Sociedade de Crédito ao Microempreendedor e à Empresa de Pequeno Porte Ltda.",
  "Neon Pagamentos S.A.",
  "Nubank Pagamentos S.A.",
  "Omni Banco S.A.",
  "Órama Distribuidora de Títulos e Valores Mobiliários S.A.",
  "PagBank PagSeguro Internet S.A.",
  "PagSeguro Internet S.A.",
  "PicPay Bank – Banco Múltiplo S.A.",
  "QI Sociedade de Crédito Direto S.A.",
  "Quero-Quero Verdecard Instituição de Pagamento S.A.",
  "RecargaPay Instituição de Pagamento Ltda.",
  "Revolut Brasil Instituição de Pagamento Ltda.",
  "Santander Brasil S.A.",
  "Sicredi",
  "Stone Pagamentos S.A.",
  "SumUp Sociedade de Crédito Direto S.A.",
  "Super Pagamentos e Administração de Meios Eletrônicos S.A.",
  "Travelex Banco de Câmbio S.A.",
  "Unicred Cooperativa",
  "Uniprime Norte do Paraná – Cooperativa de Crédito Ltda.",
  "Will Financeira S.A. Crédito Financiamento e Investimento",
  "Wise Brasil Corretora de Câmbio Ltda.",
  "Zema Crédito Financiamento e Investimento S.A.",
];

export const BANCOS_BRASIL: readonly string[] = [...RAW].sort((a, b) =>
  a.localeCompare(b, "pt-BR", { sensitivity: "base" })
);
